name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:17
          apps: sbt

      - name: Warm up scala-cli Bloop server
        run: echo 'object W' > /tmp/W.scala && scala-cli compile /tmp/W.scala

      - run: ./mill _.test
